### ISSUE TITLE
Autodiscover with WebCredentials on (non-windows) fails

### ISSUE THREAD

**Issue by deeprobin** [sherlock1982/ews-managed-api#64]
```
[08:29:01.879][ERR] (14) Autodiscover ****@****.**** with user ***** failed System.ArgumentNullException: Value cannot be null. (Parameter 'uriPrefix')
   at System.Net.CredentialCache.Add(Uri uriPrefix, String authType, NetworkCredential cred)
   at Microsoft.Exchange.WebServices.Data.ExchangeServiceBase.AdjustLinuxAuthentication(Uri url, ExchangeCredentials serviceCredentials)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.PrepareHttpClient()
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverRequest.InternalExecute()
   at Microsoft.Exchange.WebServices.Autodiscover.GetUserSettingsRequest.Execute()
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.InternalGetUserSettings(List`1 smtpAddresses, List`1 settings, Nullable`1 requestedVersion, Uri& autodiscoverUrl)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetSettings[TGetSettingsResponseCollection,TSettingName](List`1 identities, List`1 settings, Nullable`1 requestedVersion, GetSettingsMethod`2 getSettingsMethod, Func`1 getDomainMethod)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetUserSettings(List`1 smtpAddresses, List`1 settings)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.InternalGetSoapUserSettings(String smtpAddress, List`1 requestedSettings)
   at Microsoft.Exchange.WebServices.Autodiscover.AutodiscoverService.GetUserSettings(String userSmtpAddress, UserSettingName[] userSettingNames)
   at Microsoft.Exchange.WebServices.Data.ExchangeService.GetAutodiscoverUrl(String emailAddress, ExchangeVersion requestedServerVersion, AutodiscoverRedirectionUrlValidationCallback validateRedirectionUrlCallback)
   at Microsoft.Exchange.WebServices.Data.ExchangeService.AutodiscoverUrl(String emailAddress, AutodiscoverRedirectionUrlValidationCallback validateRedirectionUrlCallback)
   at InboxCleanup.Exchange.AutoDiscoverService.<TryAutoDiscover>b__4_1(CancellationToken ct) in /src/tools/InboxCleanup/Exchange/AutoDiscoverService.cs:line 33
```

**Comment by deeprobin** [comment]
closing this - EWS will not be longer supported & last commit in this repo is old
