### ISSUE TITLE
Microsoft.Exchange.WebServices.Data.ServiceResponseException: The mailbox does not have SMTP address associated with it.

### ISSUE THREAD

**Issue by dkekesi** [sherlock1982/ews-managed-api#72]
When trying to find folders on an Exchange 2016 server, I get this error:
System.AggregateException: One or more errors occurred. ---> Microsoft.Exchange.WebServices.Data.ServiceResponseException: The mailbox does not have SMTP address associated with it.
   at Microsoft.Exchange.WebServices.Data.ServiceResponse.InternalThrowIfNecessary()
   at Microsoft.Exchange.WebServices.Data.MultiResponseServiceRequest`1.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Exchange.WebServices.Data.ExchangeService.<FindFolders>d__20.MoveNext()
The mailbox works, I can send mails to it.
I tried to find the exception message in the code, but I couldn't. Do you know what may cause this issue?

**Comment by dkekesi** [comment]
<?xml version="1.0" encoding="utf-16"?>
<Trace Tag="EwsResponse" Tid="23" Time="2024-06-12 15:49:57Z" Version="15.0.913.15">
  <s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/">
    <s:Header>
      <h:ServerVersionInfo MajorVersion="15" MinorVersion="2" MajorBuildNumber="986" MinorBuildNumber="26" Version="V2017_07_11" xmlns:h="http://schemas.microsoft.com/exchange/services/2006/types" xmlns="http://schemas.microsoft.com/exchange/services/2006/types" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" />
    </s:Header>
    <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <m:FindFolderResponse xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types">
        <m:ResponseMessages>
          <m:FindFolderResponseMessage ResponseClass="Error">
            <m:MessageText>The mailbox does not have SMTP address associated with it.</m:MessageText>
            <m:ResponseCode>ErrorNonExistentMailbox</m:ResponseCode>
            <m:DescriptiveLinkKey>0</m:DescriptiveLinkKey>
            <m:MessageXml>
              <t:Value Name="MailboxGuid" />
            </m:MessageXml>
          </m:FindFolderResponseMessage>
        </m:ResponseMessages>
      </m:FindFolderResponse>
    </s:Body>
  </s:Envelope>
</Trace>

This is the response produced by the trace. This also has the error message, so it seems that the server is producing the error.
